package com.cringland.ni.repository.model;

import java.util.Set;

import org.springframework.data.annotation.Id;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIgnore;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.With;

@DynamoDBTable(tableName = "Review")
@Data
@AllArgsConstructor
@NoArgsConstructor
@With
@Builder
public class ReviewItem {

    @Id
    @DynamoDBIgnore
    private ReviewKey key;
    private String author;
    private String title;
    private String text;
    private int rating;
    private Set<String> imageIds;

    @DynamoDBHashKey
    public String getId() {
        return (key != null) ? key.getId() : null;
    }

    public void setId(String vendorId) {
        if (key == null) {
            key = new ReviewKey();
        }
        key.setId(vendorId);
    }

    @DynamoDBRangeKey
    public String getBucketItemSlug() {
        return (key != null) ? key.getBucketItemSlug() : null;
    }

    public void setBucketItemSlug(String product) {
        if (key == null) {
            key = new ReviewKey();
        }
        key.setBucketItemSlug(product);
    }
}

