const countryAntrimTowns = ['Aghagallon',
  'Aghalee',
  'Ahoghill',
  'Aldergrove',
  'Antrim',
  'Armoy',
  'Aughnadeagh',
  'Ballinderry',
  'Ballintoy',
  'Ballybogy',
  'Ballycarry',
  'Ballycastle',
  'Ballyclare',
  'Ballyeaston',
  'Ballygalley',
  'Ballygelly',
  'Ballylesson',
  'Ballylumford',
  'Ballymena',
  'Ballymoney',
  'Ballynure',
  'Ballyskeagh',
  'Ballyvoy',
  'Balnamore',
  'Belfast',
  'Belfast City',
  'Beltoy',
  'Bendooragh',
  'Broughshane',
  'Buckna',
  'Bushmill',
  'Bushmills',
  'Caddy',
  'Cape Castle',
  'Carnalbanagh Sheddings',
  'Carncastle',
  'Carnlough',
  'Carnmoney',
  'Carrickfergus',
  'Castlecat',
  'Causeway coast',
  'Clady',
  'Clogh',
  'Clogh Mills',
  'Cloughmills',
  'Corkey',
  'Correen',
  'Craigs',
  'Crumlin',
  'Cullybackey',
  'Cushendall',
  'Cushendum',
  'Cushendun',
  'Damhead',
  'Derriaghy',
  'Derrykeighan',
  'Dervock',
  'Doagh',
  'Drumbeg',
  'Drumnagreagh Port',
  'Dunadry',
  'Dundrod',
  'Dunloy',
  'Dunmurry',
  'Dunseverick',
  'Eden',
  'Finvoy',
  'Five Corners',
  'Flatfield',
  'Galgorm',
  'Garryduff',
  'Glarryford',
  'Glenaan',
  'Glenariff',
  'Glenariff (or waterfoot)',
  'Glenarm',
  'Glenavy',
  'Glengormely',
  'Glenoe',
  'Glenvale',
  'Glynn',
  'Gracehill',
  'Greenisland',
  'Hannahstown',
  'Hillhall',
  'Hyde Park',
  'Islandmagee',
  'Kells',
  'Killead',
  'Killinaboy',
  'Killybegs',
  'Kilraghts',
  'Kilwaughter',
  'Kirkhills',
  'Knockaholet',
  'Lagavara',
  'Lambeg',
  'Larne',
  'Legoniel',
  'Lisburn',
  'Loanends',
  'Loughguile',
  'Maghaberry',
  'Magheraberry',
  'Magheramorne',
  'Mallusk',
  'Martinstown',
  'Mazetown',
  'McLaughlins Corner',
  'Mill Town Millbrook',
  'Millford',
  'Moneyglass',
  'Monkstown',
  'Moorfields',
  'Moss-side',
  'Mosside',
  'Mossley',
  'Muckamore',
  'Mullan Head',
  'Newferry',
  'Newtown-Crommelin',
  'Newtownabbey',
  'Nutts Corner',
  'Parkgate',
  'Pharis',
  'Portballintrae',
  'Portglenone',
  'Portmuck',
  'Portrush',
  'Quarrytown',
  'Randalstown',
  'Rasharkin',
  'Rathlin island',
  'Revallagh',
  'Staffordstown',
  'Stonyford',
  'Straid',
  'Stranocum',
  'Templepatrick',
  'Templeshanbo',
  'The Diamond',
  'The Dry Arch',
  'The Five Roads',
  'The Spa',
  'Toome',
  'Toomebridge',
  'Waterfoot',
  'Whiteabbey',
  'Whitehead',
  'Whiteside Corner',
  'Woodburn',
  'Woodgreen'
];

const countryDownTowns = ['Annaclone',
  'Annacloy',
  'Annadorn',
  'Annahilt',
  'Annalong',
  'Annsborough',
  'Ardglass',
  'Ardkeen',
  'Attical',
  'Baileysmill',
  'Balliggan',
  'Ballinran',
  'Balloo',
  'Ballygowan',
  'Ballyhalbert',
  'Ballyhornan',
  'Ballykeel',
  'Ballymartin',
  'Ballynaguilkee',
  'Ballynahinch',
  'Ballyroney',
  'Ballywalter',
  'Ballyward',
  'Banbridge',
  'Bangor',
  'Barnmeen',
  'Bishops Court',
  'Bleary',
  'Boardmills',
  'Bryansford',
  'Burren',
  'Carrowdore',
  'Carryduff',
  'Castlereagh',
  'Castlewellan',
  'Chapeltown',
  'Church Ballee',
  'Churchtown',
  'Cloghroe',
  'Clough',
  'Cloughey',
  'Coagh',
  'Comber',
  'Conlig',
  'Corbet Milltown',
  'Craigavad',
  'Crawfordsburn',
  'Crossgar',
  'Culcavy',
  'Cultra',
  'Derryboy',
  'Donaghadee',
  'Donaghcloney',
  'Downings',
  'Downpatrick',
  'Dromahair',
  'Dromore',
  'Drumaness',
  'Drumbo',
  'Dundonald',
  'Dundrum',
  'Finnis',
  'Gilford',
  'Glastry',
  'Greencastle',
  'Greyabbey',
  'Groomsport',
  'Hillsborough',
  'Hilltown',
  'Holywood',
  'Katesbridge',
  'Kilcoo',
  'Kilkeel',
  'Killinchy',
  'Killough',
  'Killyleagh',
  'Kilmore',
  'Kilntown',
  'Kircubbin',
  'Kirkistown',
  'Loughbrickland',
  'Loughinisland',
  'Lowtown',
  'Maghera',
  'Magheralin',
  'Mayobridge',
  'McGaffins Corner',
  'Millisle',
  'Millstreet',
  'Milltown',
  'Minterburn',
  'Moira',
  'Monaghan',
  'Mount Stewart',
  'Mullartown',
  'Newcastle',
  'Newry',
  'Newtownards',
  'Portaferry',
  'Portavogie',
  'Raffrey',
  'Rathfriland',
  'Ravernet',
  'Rostrevor',
  'Rosturk',
  'Rush',
  'Saintfield',
  'Saul',
  'Scarva',
  'Seaforde',
  'Seapatrick',
  'Shrigley',
  'Six Road Ends',
  'Stormont',
  'Strangford',
  'The Cross',
  'The Sweep',
  'The Ward',
  'Tyrella',
  'Waringsford',
  'Waringstown',
  'Warrenpoint'
];

const countryArmaghTowns = ['Acton',
  'Allistragh',
  'Ardress',
  'Armagh',
  'Ballsmill',
  'Ballyleny',
  'Bannfoot',
  'Belleek',
  'Bessbrook',
  'Blackwatertown',
  'Camlough',
  'Carnagh',
  'Charlemont',
  'Cladymilltown',
  'Clonfeacle',
  'Cloughreagh',
  'Craigavon',
  'Creggan',
  'Crossmaglen',
  'Cullyhanna',
  'Darkley',
  'Derryadd',
  'Derrynoose',
  'Dollingstown',
  'Flurrybridge',
  'Forkhill',
  'Forkill',
  'Hamiltonsbawn',
  'Jerrettspass',
  'Jonesborough',
  'Keady',
  'Kilclief',
  'Killylea',
  'Kilmore',
  'Kingsmills',
  'Laurelvale',
  'Lislea',
  'Lisnadill',
  'Loughgall',
  'Lurgan',
  'Markethill',
  'Middletown',
  'Milford',
  'Milltown',
  'Mountnorris',
  'Mullaghbane',
  'Newtownhamilton',
  'Portadown',
  'Poyntz Pass',
  'Richhill',
  'Richill',
  'Scotch Street',
  'Tandragee',
  'Tassagh',
  'Tullyroan Corner',
  'Tynan',
  'Wells Cross',
  'Whitecross'
];

const countryFermanaghTowns = ['Aghanglack',
  'Ballinamallard',
  'Belcoo',
  'Belcoo east',
  'Bellanaleck',
  'Belleek',
  'Bellek',
  'Blaney',
  'Boho',
  'Brookeborough',
  'Clabby',
  'Clonelly',
  'Clontivrin',
  'Cooneen',
  'Derrygonnelly',
  'Derrylin',
  'Devenish',
  'Donagh',
  'Drumskinny',
  'Ederney',
  'Enniskillen',
  'Florececourt',
  'Florence Court',
  'Florencecourt',
  'Garrison',
  'Holywell',
  'Irvinestown',
  'Kesh',
  'Killadeas',
  'Killyrover',
  'Kilskeery',
  'Kinawley',
  'Lack',
  'Letterbreen',
  'Lisaskea',
  'Lisbellaw',
  'Lisnarick',
  'Lisnarrick',
  'Lisnaskea',
  'Mackan',
  'Magheraveely',
  'Maguiresbridge',
  'Marble Arch',
  'Newtownbutler',
  'Roslea',
  'Rosscor',
  'Springfield',
  'Tamlaght',
  'Teer',
  'Termon',
  'White Island'];

const countryDerryTowns = ['Aghadowey',
  'Agivey',
  'Articlave',
  'Ballybane',
  'Ballykelly',
  'Ballylintagh',
  'Ballyrashane',
  'Ballyronan',
  'Ballywildrick',
  'Baranailt',
  'Beechgrove',
  'Bellaghy',
  'Blagh',
  'Bolea',
  'Boleran',
  'Bovedy',
  'Bovevagh',
  'Caheny',
  'Carn',
  'Carnanreagh',
  'Castledawson',
  'Castledsawson',
  'Castlerock',
  'Claudy',
  'Coleraine',
  'Craigavole',
  'Crindle',
  'Crossgare',
  'Culnady',
  'Curran',
  'Derry',
  'Desertmartin',
  'Dowling',
  'Draperstown',
  'Drumahoe',
  'Drumsurn',
  'Dungiven',
  'Eglinton',
  'Feeny',
  'Garvagh',
  'Glen',
  'Glenhead',
  'Gortnahey',
  'Greysteel',
  'Inishrush',
  'Killykergan',
  'Kilrea',
  'Knockcloghrim',
  'Labby',
  'Letterloan',
  'Limavady',
  'Lisnamuck',
  'Londonderry',
  'Macosquin',
  'Maghera',
  'Magherafelt',
  'Magilligan',
  'Margymonaghan',
  'Moneydig',
  'Moneymore',
  'Moneyneany',
  'Moys',
  'Mullan',
  'New Buildings',
  'Portstewart',
  'Scriggan',
  'Spring Town',
  'Swatragh',
  'The Rock',
  'Tobermore',
  'Upperlands'];

const countryTyroneTowns = ['Altmore House',
  'Arboe',
  'Ardstraw',
  'Ardtrea',
  'Artigarvan',
  'Augher',
  'Aughmullan',
  'Aughnacloy',
  'Ballygawley',
  'Ballymagorry',
  'Ballynamallaght',
  'Ballyneaner',
  'Ballyreagh',
  'Ballywholan',
  'Benburb',
  'Beragh',
  'Bodoney',
  'Bready',
  'Brigh',
  'Cabragh',
  'Caledon',
  'Cappagh',
  'Carland',
  'Carnteel',
  'Carrickmore',
  'Castlecaufield',
  'Castlederg',
  'Church Hill',
  'Clady',
  'Cloghbrack',
  'Cloghcor',
  'Cloghera',
  'Coaghg',
  'Coalisland',
  'Cookstown',
  'Coolmaghry',
  'Craig',
  'Cranagh',
  'Creggan',
  'Crilly',
  'Donaghmore',
  'Dromore',
  'Drumnakilly',
  'Drumquin',
  'Dungannon',
  'Dunnamanagh',
  'Dunnamore',
  'Dyan',
  'Eglish',
  'Eskragh',
  'Fintona',
  'Fivemiletown',
  'Garvaghy',
  'Glebe',
  'Gortaclady',
  'Gortin',
  'Gortreagh',
  'Grant House',
  'Granville',
  'Greencastle',
  'Greystone',
  'Kildress',
  'Killeen',
  'Killen',
  'Killeter',
  'Killyclogher',
  'Kingsmill',
  'Knockmany',
  'Laghey Corner',
  'Liscloon',
  'Lisdoart',
  'Magheramason',
  'Milltown',
  'Mitchelstown',
  'Mountfield',
  'Mountjoy',
  'Moy',
  'Moygashel',
  'Newmills',
  'Newtownstewart',
  'Omagh',
  'Oritor',
  'Plumbridge',
  'Pomeroy',
  'Reclain',
  'Ruan',
  'Sandholes',
  'Seskinore',
  'Sess Kilgreen',
  'Sion Mills',
  'Sixmilecross',
  'Sperrin',
  'Stewartstown',
  'Strabane',
  'Tamnamore',
  'Teemore',
  'The Downs',
  'The Pigeons',
  'The Rower',
  'Trillick',
  'Tullyhogue',
  'Victoria Bridge'];

export function counties() {
  return ["Antrim", "Londonderry", "Down", "Fermanagh", "Armagh", "Tyrone"];
}

export function towns() {
  return [
    ...countryAntrimTowns,
    ...countryDerryTowns,
    ...countryDownTowns,
    ...countryFermanaghTowns,
    ...countryTyroneTowns,
    ...countryArmaghTowns,
  ]
}

export function county(town) {
  if (countryAntrimTowns.includes(town))
    return "Antrim";
  if (countryDownTowns.includes(town))
    return "Down";
  if (countryDerryTowns.includes(town))
    return "Londonderry";
  if (countryTyroneTowns.includes(town))
    return "Tyrone";
  if (countryFermanaghTowns.includes(town))
    return "Fermanagh";
  if (countryTyroneTowns.includes(town))
    return "Tyrone";
}
